//
//  TextContent.swift
//  Diwi
//
//  Created by Dominique Miller on 7/16/19.
//  Copyright © 2019 Trim Agency. All rights reserved.
//

import Foundation

// Place all string literals here!
struct TextContent {
    
    struct Labels {
        static let addLocation = "ADD LOCATION"
        static let saveLocationToEvent = "SAVE LOCATION TO EVENT"
        static let addEventToItem = "ADD EVENT TO ITEM"
        static let addDateToItem = "ADD DATE TO ITEM"
        static let addDateToLook = "ADD DATE TO LOOK"
        static let addItems = "Add Items"
        static let addDateToFriend = "ADD DATE TO FRIEND"
        static let addNewEventToItem = "ADD NEW EVENT TO ITEM"
        static let addEventsWithFriend = "ADD EVENTS WITH FRIEND"
        static let addLooksWithFriend = "ADD LOOKS WITH FRIEND"
        static let addItemsWithFriend = "ADD ITEMS WITH FRIEND"
        static let addItemsToEvent = "ADD ITEMS TO EVENT"
        static let addItemsToLook = "ADD ITEMS TO LOOK"
        static let addLooksToEvent = "ADD LOOKS TO EVENT"
        static let addLooksToItem = "ADD LOOKS TO ITEM"
        static let addEventToLook = "ADD EVENT TO LOOK"
        static let addEvent = "ADD EVENT"
        static let addANote = "Add a note:"
        static let addFriends = "ADD FRIENDS"
        static let cancel = "CANCEL"
        static let closet = "Did I Wear It?!"
        static let contacts = "WHO DID I WEAR IT WITH?"
        static let events = "WHERE DID I WEAR IT?"
        static let event = "Event"
        static let editItem = "EDIT ITEM"
        static let editEvent = "EDIT EVENT"
        static let dateAdded = "Date Added:"
        static let forgotPassword = "FORGOT PASSWORD"
        static let profile = "PROFILE"
        static let calendar = "WHEN DID I WEAR IT?"
        static let newItem = "NEW ITEM"
        static let itemSaved = "This item has been saved to your closet."
        static let pressButtonToAddEvent = "Press the blue arrow to start"
        static let noEvents = "It appears you have no events scheduled for the month. To get started press a date to add an event."
        static let time = "Time"
        static let location = "Location"
        static let lookItems = "Look Items"
        static let looks = "Looks"
        static let myFriend = "MY FRIEND"
        static let myLook = "MY LOOK"
        static let myItem = "MY ITEM"
        static let myEvent = "MY EVENT"
        static let saveThisItemToAnEventOn = "Save this item to an event on "
        static let defaultSaveItemToEvent = "Save this item to event."
        static let noEventScheduledOnDay = "There is no event scheduled for this day would you like to create an event?"
        static let removeItemFromCloset = "REMOVE ITEMS"
        static let removeLookFromCloset = "REMOVE LOOKS"
        static let removeFriends = "REMOVE FRIENDS"
        static let removeItems = "REMOVE ITEMS"
        static let removeLooks = "REMOVE LOOKS"
        static let removeEvents = "REMOVE EVENTS"
        static let removeEvent = "REMOVE EVENT"
        static let removeEventsFromCalendar = "REMOVE EVENTS FROM CALENDAR"
        static let removeEventFromCalendar = "Are you sure you wish to remove this event from your calendar?"
        static let removeFriendsInfo = "Are you sure you wish to remove these friends?"
        static let removeClothingItemsFromCloset = "Are you sure you wish to remove these items?"
        static let removeLooksFromCloset = "Are you sure you wish to remove these looks?"
        static let scheduledEvent = "MY EVENT"
        static let saveProfile = "SAVE PROFILE"
        static let saveItem = "SAVE ITEM"
        static let startBy = "START BY PICKING AN EVENT DATE"
        static let who = "WHO?"
        static let whoWasAtEvent = "Who was at the event?"
        static let whatDidIWear = "What did I wear?"
        static let whatIWore = "What I Wore"
        static let whatDidIWearAllCaps = "WHAT DID I WEAR?"
        static let whenIworeIt = "When I Wore It?"
        static let whereIWent = "Where I Went?"
        static let whenIWentOut = "When I Went Out"
        static let whenWasTheEvent = "When Was The Event?"
        static let whereIWoreIt = "Where I Wore It?"
        static let whoIWoreItWith = "Who I Wore It With?"
        static let whoDidIWearItWith = "WHO DID I WEAR IT WITH?"
        static let whoWasThere = "Who Was There?"
    }
    
    struct Buttons {
        static let addFriends = "ADD FRIENDS"
        static let addItemsToEvent = "ADD ITEMS TO EVENT"
        static let addItems = "ADD ITEMS"
        static let addEvents = "ADD EVENTS"
        static let addToEvent = "ADD TO EVENT"
        static let addFromCloset = "ADD FROM CLOSET"
        static let addToCalendar = "ADD TO CALENDAR"
        static let addPeopleToEvent = "ADD PEOPLE TO EVENT"
        static let addLooks = "ADD LOOKS"
        static let login = "LOGIN"
        static let done = "Done"
        static let ok = "OK"
        static let error = "Error"
        static let forgotPassword = "Forgot Your Password?"
        static let dontHaveAccount = "Don't have an account? Create one."
        static let createAccount = "CREATE ACCOUNT"
        static let sortCloset = "Sort Closet"
        static let sortEvents = "Sort Events"
        static let byEvent = "by event date"
        static let byType = "by type"
        static let byLatestDate = "by latest date"
        static let byEarliestDate = "by earliest date"
        static let alphabetically = "alphabetically"
        static let chronological = "chronological"
        static let closetItem = "CLOSET ITEM"
        static let items = "ITEMS"
        static let logout = "Log Out"
        static let looks = "LOOKS"
        static let saveItem = "SAVE ITEM"
        static let takePhoto = "TAKE A PHOTO"
        static let saveEvent = "SAVE EVENT"
        static let saveItemToEvent = "SAVE ITEM TO EVENT"
        static let cancel = "CANCEL"
        static let createEvent = "CREATE EVENT"
        static let sendEmail = "SEND EMAIL"
        static let editProfile = "EDIT PROFILE INFO"
        static let removeFriends = "REMOVE FRIENDS"
        static let removeItems = "REMOVE ITEMS"
        static let removeLooks = "REMOVE LOOKS"
        static let saveFriend = "SAVE FRIEND"
        static let saveFriends = "SAVE FRIENDS"
        static let saveLook = "SAVE LOOK"
        static let saveDateToLook = "SAVE DATE TO LOOK"
        static let saveDateToItem = "SAVE DATE TO ITEM"
        static let saveDateWithFriend = "SAVE DATE WITH FRIEND"
        static let saveLooksWithFriend = "SAVE LOOKS WITH FRIEND"
        static let saveLooksToEvent = "SAVE LOOKS TO EVENT"
        static let saveLooksToItem = "SAVE LOOKS TO ITEM"
        static let saveItemsWithFriend = "SAVE ITEMS WITH FRIEND"
        static let saveItemsToLook = "SAVE ITEMS TO LOOK"
        static let saveItemsToEvent = "SAVE ITEMS TO EVENT"
        static let saveEventsWithFriend = "SAVE EVENTS WITH FRIEND"
        static let saveEventsToLook = "SAVE EVENTS TO LOOK"
        static let saveEventsToItem = "SAVE EVENTS TO ITEM"
        static let back = "BACK"
        static let userContent = "USE CONTENT"
        static let choosePlan = "Choose Plan"
    }
    
    struct Data {
        static let alphabet = ["a", "b", "c", "d", "e", "f",
                               "g", "h", "i", "j", "k", "l",
                               "m", "n", "o", "p", "q", "r",
                               "s", "t", "u", "v", "w", "x",
                               "y", "z", "#"]
    }
    
    struct Placeholders {
        static let addNewFriend = "Add a new friend's name"
        static let username = "Username"
        static let password = "Password"
        static let passwordConfirm = "Confirm Password"
        static let email = "Email"
        static let friendName = "Friend Name"
        static let agreeTerms = "I agree to all the terms and conditions"
        static let viewTerms = "view terms and conditions"
        static let itemTitle = "Item Title"
        static let itemType = "Item Type"
        static let lookTitle = "Look Title"
        static let nameOfEvent = "Event Name"
        static let address = "Address"
        static let city = "City"
        static let state = "State"
        static let search = "search for what, where, when or who…"
        static let searchBy = "Search by date, friend, or keyword"
        static let zipCode = "Zip Code"
    }
    
    struct Errors {
        static let createTagError = "Unable to create your friend! Please try again later!"
        static let createLookError = "Unable to create your look! Please try again later!"
        static let networkNotAvailable = "No internet connection was found! Please try again later!"
        static let oops = "Oops"
        static let needToAddMoreItems = "Please select clothing items to add to your event!"
        static let clothingTypes = "Unable to get clothing types, please try again later."
        static let savingClothingItem = "Unable to save clothing item, please try again later."
        static let deletingEvent = "Unable to delete your event, please try again later"
        static let couldNotRetrieveEvent = "Unable to retrieve your event, please try again later."
        static let couldNotRetrieveLook = "Unable to retrieve your look, please try again later."
        static let noMatchingEventsFound = "No matching events with that person."
        static let noResultsFound = "No results found."
        static let passwordsDoNotMatch = "Passwords must match"
        static let searchError = "Unable to make your query, please try again later."
        static let tagIndexError = "Unable to retrieve your friends list, please try again later."
        static let underConstruction = "Under Construction"
        static let updateClothingItem = "Unable to update clothing item, please try again later."
        static let unAbleToDequeueCollectionCell = "Unable to Dequeue Reusable Collection View Cell"
        static let unsupportedWorkflow = "not supporting this workflow yet"
    }
    
    struct Fonts {
        static let diwiFont = "Project Font here"
    }
    
    struct Images {
        static let addEventWhite = "add_event_white"
        static let addIcon = "addIcon"
        static let addIconblue = "addIconBlue"
        static let addIconWhite = "addIcon_white"
        static let trimLogo = "trim-logo"
        static let homepageBackground = "homepageBackground"
        static let registrationBackground = "registrationBackground"
        static let logo1 = "logo1"
        static let logo2 = "logo2"
        static let backIcon = "backIcon"
        static let backIconWhite = "backIconWhite"
        static let checkbox = "checkboxEnabled"
        static let contactsLarge = "contacts_large"
        static let profileIcon = "profileIcon"
        static let hangerIconActive = "hangerIconActive"
        static let hangerIconWhite = "hangerIconWhite"
        static let hangerLarge = "hanger_large"
        static let calendarIcon = "calendarIcon"
        static let calendarIconGray = "calendarIconGray"
        static let calendarIconActive = "calendarActive"
        static let calendarSelected = "calendar-selected"
        static let cameraIcon = "cameraIcon"
        static let cameraUnselected = "camera-unselected"
        static let closetEmptyState = "closetEmptyState"
        static let closetIcon = "closetIcon"
        static let closetSelected = "closet-selected"
        static let clockIcon = "clock_icon"
        static let contactIconWhite = "contactIcon"
        static let contactSelected = "contact_dark_icon"
        static let contactIcon = "contacts-unselected"
        static let downArrowIcon = "downArrow"
        static let eventIconActive = "eventIconActive"
        static let editItemButton = "editItemButton"
        static let eventEmptyState = "eventEmptyState"
        static let eventSelected = "events-selected"
        static let eventIcon = "events-unselected"
        static let homePageIcon = "homePageIcon"
        static let rightArrow = "rightArrow"
        static let rightArrowButton = "rightArrowButton"
        static let leftArrow = "leftArrow"
        static let cheersIcon = "cheersIcon"
        static let moreIcon = "moreIcon"
        static let searchIcon = "searchIcon"
        static let searchIconBlue = "searchIconBlue"
        static let checkBoxBlue = "checkBoxBlue"
        static let pinkDownArrow = "pinkDownArrow"
        static let pinkChampagne = "pink_champagne"
        static let pinkHanger = "pink_hanger"
        static let pinkContacts = "pink_contacts"
        static let closeBtn = "closeButton"
        static let addIconNoBackground = "addIcon_noBackground"
        static let location = "location"
        static let removePink = "removePink"
        static let smallDelete = "smallDelete"
        static let searchArrow = "search_arrow"
        static let pinkIconEvent = "pinkIconEvent"
        static let whatBubble = "WHAT?"
        static let whatOnboarding = "whatOnboarding"
        static let whatBackground = "whatBackground"
        static let whenBubble = "WHEN?"
        static let whenOnboarding = "whenOnboarding"
        static let whenBackground = "whenBackground"
        static let whereBackground = "whereBackground"
        static let whereOnboarding = "whereOnboarding"
        static let whereBubble = "WHERE?"
        static let whoBubble = "WHO?"
        static let whoOnboarding = "whoOnboarding"
        static let whoBackground = "whoBackground"
		static let accountIcon = "accountIcon"
		static let accountIconSelected = "accountIcon-selected"
        static let accountBlueIconSelected = "filledbluecircle"

        
    }
    
    struct Models {
        static let event         = "Event"
        static let tag           = "Friend"
        static let look          = "Look"
        static let clothingItem  = "ClothingItem"
    }
    
    struct KeyPaths {
        static let user = "user"
        static let passwordReset = "password_reset"
    }
    
    struct Alert {
        static let cancel = "Cancel"
        static let camera = "TAKE A PHOTO"
        static let photoLibrary = "ADD PHOTO FROM GALLERY"
        static let selectMediaType = "Choose media type for clothing item"
        static let duplicateName = "Duplicate name!"
        static let duplicateNameMessage = "You already have a Friend with that name. Want to add a different one?"
    }
    
    struct Onboarding {
        static let whatText = "Take photos of WHAT look you wore..."
        static let whereText = "Keep track of WHERE you went..."
        static let whenText = "And WHEN you wore it..."
        static let whoText = "Reminders of WHO you were with!"
        static let skipThis = "SKIP THIS"
    }
    
    struct SearchLabels {
        static let upcomingEvent = "An upcoming event"
        static let pastEvent     = "A past event"
        static let contact       = "A friend"
        static let look          = "Look in your closet"
        static let item          = "Item in your closet"
    }
}
